version: '3.8'

services:
  postgres-ms:
    image: postgres:latest
    container_name: postgres-ms
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=posgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

  redis-ms:
    image: redis:latest
    container_name: redis-ms
    ports:
      - "6379:6379"
    networks:
      - network

  app:
    build: .
    container_name: app-ms
    ports:
      - "8080:8080"
    depends_on:
      - postgres-ms
      - redis-ms
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-ms:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=posgres
      - SPRING_REDIS_HOST=redis-ms
      - SPRING_REDIS_PORT=6379
    networks:
      - network
    links:
      - redis-ms

volumes:
  postgres_data:

networks:
  network:
    driver: bridge